name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Install required Node.js version
        uses: actions/setup-node@v3
        
      - name: Run tests
        uses: DevExpress/testcafe-action@v0.0.6
        with:
          args: "chrome tests --reporter xunit:reports/xunit/report.xml --app 'yarn npx http-server' --app-init-delay 60000"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: reports/xunit/report.xml
          retention-days: 5
